package es.uma.proyecto.tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.uma.informatica.sii.anotaciones.Requisitos;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;

public class ProyectoIT {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	private static final String UNIDAD_PERSISTENCIA_PRUEBAS = "proyectoIT";

	private static String baseURL;
	private static Map<String, String> propiedadesExtra = new HashMap<>();

	@BeforeClass
	public static void setupClass() {
		String server = "localhost";
		try (InputStream is = ProyectoIT.class.getClassLoader().getResourceAsStream("pom.properties")) {
			Properties pomProperties = new Properties();
			pomProperties.load(is);
			server = pomProperties.getProperty("server.host");
			String databaseURL = "jdbc:mysql://" + server + ":3306/sii";
			propiedadesExtra.put("javax.persistence.jdbc.url", databaseURL);
		} catch (IOException e) {
			e.printStackTrace();
		}
		baseURL = "http://" + server + ":8080/DigitalSolutions-war/";
	}

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();

//			BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA_PRUEBAS);

	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	@Requisitos({"RF1"})
	//comprueba que un admin no se puede logear en el login de los clientes
	public void loginADFail() {
		driver.get(baseURL);
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("login:loginUsername")).click();
		driver.findElement(By.id("login:loginUsername")).sendKeys("ponciano");
		driver.findElement(By.id("login:loginPassword")).sendKeys("ponciano");
		driver.findElement(By.id("login:loginBoton")).click();
		assertThat(driver.findElement(By.cssSelector("li")).getText(), is("La cuenta no existe"));
	}

	@Test
	@Requisitos({"RF2"})
	//coamprueba si se puede dar de alta una empresa, si se redirige al panel administrativos habia exito
	public void altaClienteEmp() {
		driver.get("http://localhost:8080/DigitalSolutions-war/admin.xhtml");
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("loginAD:loginUsername")).click();
		driver.findElement(By.id("loginAD:loginUsername")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginPassword")).click();
		driver.findElement(By.id("loginAD:loginPassword")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginBotonAD")).click();
		driver.findElement(By.id("form_administrativo_inicio:AnadirClienteAdmin")).click();
		driver.findElement(By.cssSelector("td:nth-child(2)")).click();
		driver.findElement(By.cssSelector("td:nth-child(2) > label")).click();
		driver.findElement(By.id("formularioUsuario_darDeAlta:SiguienteUsuario_DarAlta")).click();
		driver.findElement(By.id("formularioEmpresa_darAlta:IdentificacionEmp_DarAltaT")).click();
		driver.findElement(By.id("formularioEmpresa_darAlta:IdentificacionEmp_DarAltaT")).sendKeys("testEM");
		driver.findElement(By.id("formularioEmpresa_darAlta:Direccion_empDarAltaT")).click();
		driver.findElement(By.id("formularioEmpresa_darAlta:Direccion_empDarAltaT")).sendKeys("d");
		driver.findElement(By.id("formularioEmpresa_darAlta:Ciudad_empDarAltaT")).click();
		driver.findElement(By.id("formularioEmpresa_darAlta:Ciudad_empDarAltaT")).sendKeys("d");
		driver.findElement(By.id("formularioEmpresa_darAlta:codigoPostal_empDarAltaT")).click();
		driver.findElement(By.cssSelector("tr:nth-child(5)")).click();
		driver.findElement(By.id("formularioEmpresa_darAlta:codigoPostal_empDarAltaT")).sendKeys("1");
		driver.findElement(By.id("formularioEmpresa_darAlta:Pais_empDarAltaT")).click();
		driver.findElement(By.id("formularioEmpresa_darAlta:Pais_empDarAltaT")).sendKeys("d");
		driver.findElement(By.id("formularioEmpresa_darAlta:RSDarAltaT")).click();
		driver.findElement(By.id("formularioEmpresa_darAlta:RSDarAltaT")).sendKeys("testEMP");
		driver.findElement(By.id("formularioEmpresa_darAlta:enviarDarAlta_emp")).click();
		driver.findElement(By.id("form_administrativo_inicio:UsuarioAdmin")).click();
		assertThat(driver.findElement(By.id("form_administrativo_inicio:UsuarioAdmin")).getText(), is("ponciano"));
		driver.close();
	}

	@Test
	@Requisitos({"RF2"})
	//comprueba que se queda en la misma pagina y se imprime un error si se quere dar de alta un cliente ya existente
	public void altaClienteExist() {
		driver.get(baseURL+"admin.xhtml");
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("loginAD:loginUsername")).click();
		driver.findElement(By.id("loginAD:loginUsername")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginPassword")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginBotonAD")).click();
		driver.findElement(By.id("form_administrativo_inicio:AnadirClienteAdmin")).click();
		driver.findElement(By.cssSelector("td:nth-child(1) > label")).click();
		driver.findElement(By.id("formularioUsuario_darDeAlta:SiguienteUsuario_DarAlta")).click();
		driver.findElement(By.id("formulario_darAltaIndividual:UsuarioInd_DarAltaT")).click();
		driver.findElement(By.id("formulario_darAltaIndividual:UsuarioInd_DarAltaT")).sendKeys("ana");
		driver.findElement(By.id("formulario_darAltaIndividual:ContrasenaInd_DarAltaT")).click();
		driver.findElement(By.id("formulario_darAltaIndividual:ContrasenaInd_DarAltaT")).sendKeys("dsa");
		driver.findElement(By.id("formulario_darAltaIndividual:IdentificacionInd_DarAltaT")).click();
		driver.findElement(By.id("formulario_darAltaIndividual:IdentificacionInd_DarAltaT")).sendKeys("ads");
		driver.findElement(By.id("formulario_darAltaIndividual:DireccionInd_DarAltaT")).click();
		driver.findElement(By.id("formulario_darAltaIndividual:DireccionInd_DarAltaT")).sendKeys("das");
		driver.findElement(By.id("formulario_darAltaIndividual:CiudadInd_DarAltaT")).click();
		driver.findElement(By.id("formulario_darAltaIndividual:CiudadInd_DarAltaT")).sendKeys("das");
		driver.findElement(By.id("formulario_darAltaIndividual:codigoPostalInd_DarAltaT")).click();
		driver.findElement(By.id("formulario_darAltaIndividual:codigoPostalInd_DarAltaT")).sendKeys("1");
		driver.findElement(By.id("formulario_darAltaIndividual:PaisInd_DarAltaT")).click();
		driver.findElement(By.id("formulario_darAltaIndividual:PaisInd_DarAltaT")).sendKeys("asd");
		driver.findElement(By.id("formulario_darAltaIndividual:NombreIInd_DarAltaT")).click();
		driver.findElement(By.id("formulario_darAltaIndividual:NombreIInd_DarAltaT")).sendKeys("sad");
		driver.findElement(By.id("formulario_darAltaIndividual:ApellidoIInd_DarAltaT")).click();
		driver.findElement(By.id("formulario_darAltaIndividual:ApellidoIInd_DarAltaT")).sendKeys("ad");
		driver.findElement(By.id("formulario_darAltaIndividual:EnviarInd_DarAlta")).click();
		driver.findElement(By.cssSelector(".d-flex li")).click();
		assertThat(driver.findElement(By.cssSelector(".d-flex li")).getText(), is("Este usuario ya existe"));
		driver.close();
	}

	@Test
	@Requisitos({"RF2"})
	//coamprueba si se puede dar de alta un individual, si se redirige al panel administrativos habia exito
	public void altaClienteInd() {
		driver.get(baseURL+"admin.xhtml");
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("loginAD:loginUsername")).click();
		driver.findElement(By.id("loginAD:loginUsername")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginPassword")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginBotonAD")).click();
		driver.findElement(By.id("form_administrativo_inicio:AnadirClienteAdmin")).click();
		driver.findElement(By.cssSelector("td:nth-child(1) > label")).click();
		driver.findElement(By.id("formularioUsuario_darDeAlta:SiguienteUsuario_DarAlta")).click();
		driver.findElement(By.id("formulario_darAltaIndividual:UsuarioInd_DarAltaT")).click();
		driver.findElement(By.id("formulario_darAltaIndividual:UsuarioInd_DarAltaT")).sendKeys("testIND");
		driver.findElement(By.id("formulario_darAltaIndividual:ContrasenaInd_DarAltaT")).sendKeys("testIND");
		driver.findElement(By.id("formulario_darAltaIndividual:IdentificacionInd_DarAltaT")).sendKeys("testINDDNI");
		driver.findElement(By.id("formulario_darAltaIndividual:DireccionInd_DarAltaT")).sendKeys("test");
		driver.findElement(By.id("formulario_darAltaIndividual:CiudadInd_DarAltaT")).sendKeys("test");
		driver.findElement(By.id("formulario_darAltaIndividual:codigoPostalInd_DarAltaT")).sendKeys("1");
		driver.findElement(By.id("formulario_darAltaIndividual:PaisInd_DarAltaT")).sendKeys("test");
		driver.findElement(By.id("formulario_darAltaIndividual:NombreIInd_DarAltaT")).sendKeys("testIndN");
		driver.findElement(By.id("formulario_darAltaIndividual:ApellidoIInd_DarAltaT")).sendKeys("testIndA");
		driver.findElement(By.id("formulario_darAltaIndividual:EnviarInd_DarAlta")).click();
		driver.findElement(By.id("form_administrativo_inicio:UsuarioAdmin")).click();
		assertThat(driver.findElement(By.id("form_administrativo_inicio:UsuarioAdmin")).getText(), is("ponciano"));
		driver.close();
	}

	@Test
	@Requisitos({"RF1"})
	//comprueba que si eres un admin te pues logear en el registro de admin
	public void loginADEx() {
		driver.get(baseURL+"admin.xhtml");
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("loginAD:loginUsername")).click();
		driver.findElement(By.id("loginAD:loginUsername")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginPassword")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginBotonAD")).click();
		assertThat(driver.findElement(By.id("AdminPanel1")).getText(), is("Informacion Personal"));
		driver.close();
	}

	@Test
	@Requisitos({"RF5"})
	//coamprueba si se puede dar de alta una cuenta segregada, si se redirige al panel administrativos habia exito
	public void abrirCuentaSeg() {
		driver.get(baseURL+"admin.xhtml");
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("loginAD:loginUsername")).click();
		driver.findElement(By.id("loginAD:loginUsername")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginPassword")).click();
		driver.findElement(By.id("loginAD:loginPassword")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginBotonAD")).click();
		driver.findElement(By.id("form_administrativo_inicio:AñadirCuentaAdmin")).click();
		driver.findElement(By.id("formulario_abrirCuenta:abrirCuentaSegregada")).click();
		driver.findElement(By.id("formulario_abrirCuentaSegregada:idSegregada_abrirCuentaT")).click();
		driver.findElement(By.id("formulario_abrirCuentaSegregada:idSegregada_abrirCuentaT")).sendKeys("Prueba");
		driver.findElement(By.id("formulario_abrirCuentaSegregada:ComisionSegregada_abrirCuentaT")).sendKeys("0");
		driver.findElement(By.id("formulario_abrirCuentaSegregada:SiguienteSegregada_abrirCuenta")).click();
		assertThat(driver.findElement(By.id("form_administrativo_inicio:UsuarioAdmin")).getText(), is("ponciano"));
		driver.close();
	}

	@Test
	@Requisitos({"RF10"})
	//compruba si puedes logearte como individual y te lleva a la pagina de cuentas
	public void accesoInd() {
		driver.get(baseURL);
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("login:loginUsername")).click();
		driver.findElement(By.id("login:loginUsername")).sendKeys("juan");
		driver.findElement(By.id("login:loginPassword")).click();
		driver.findElement(By.id("login:loginPassword")).sendKeys("juan");
		driver.findElement(By.id("login:loginBoton")).click();
		driver.findElement(By.cssSelector(".d-flex:nth-child(5)")).click();
		assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Cuentas disponibles"));
		driver.close();
	}

	@Test
	@Requisitos({"RF10"})
	//compruba si puedes logearte como persona autorizada y te lleva a la pagina de empresas
	public void accesoPA() {
		driver.get(baseURL);
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("login:loginUsername")).click();
		driver.findElement(By.id("login:loginUsername")).sendKeys("ana");
		driver.findElement(By.id("login:loginPassword")).click();
		driver.findElement(By.id("login:loginPassword")).sendKeys("ana");
		driver.findElement(By.id("login:loginBoton")).click();
		driver.findElement(By.cssSelector(".d-flex:nth-child(5)")).click();
		assertThat(driver.findElement(By.id("paViewH1")).getText(), is("Elige la empresa"));
		driver.close();
	}

	@Test
	@Requisitos({"RF6"})
	//comprueba si se puede dar de alta una persona autorizada y asociar esta a una empresa, si se redirige al panel administrativos habia exito 
	public void addAutorizadoYAutorizacion() {
		driver.get(baseURL+"admin.xhtml");
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("loginAD:loginUsername")).click();
		driver.findElement(By.id("loginAD:loginUsername")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginPassword")).click();
		driver.findElement(By.id("loginAD:loginPassword")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginBotonAD")).click();
		driver.findElement(By.id("form_administrativo_inicio:AnadirClienteAdmin")).click();
		driver.findElement(By.cssSelector("td:nth-child(3) > label")).click();
		driver.findElement(By.id("formularioUsuario_darDeAlta:SiguienteUsuario_DarAlta")).click();
		driver.findElement(By.id("formularioPA_darDeAlta:UsuarioPA_DarAltaT")).click();
		driver.findElement(By.id("formularioPA_darDeAlta:UsuarioPA_DarAltaT")).sendKeys("paTest");
		driver.findElement(By.id("formularioPA_darDeAlta:ContrasenaPA_DarAltaT")).click();
		driver.findElement(By.id("formularioPA_darDeAlta:ContrasenaPA_DarAltaT")).sendKeys("oaTest");
		driver.findElement(By.id("formularioPA_darDeAlta:IdentificacionPA_DarAltaT")).click();
		driver.findElement(By.id("formularioPA_darDeAlta:IdentificacionPA_DarAltaT")).sendKeys("paTestDNI");
		driver.findElement(By.id("formularioPA_darDeAlta:DireccionPA_DarAltaT")).click();
		driver.findElement(By.id("formularioPA_darDeAlta:DireccionPA_DarAltaT")).sendKeys("a");
		driver.findElement(By.id("formularioPA_darDeAlta:CiudadPA_DarAltaT")).click();
		driver.findElement(By.id("formularioPA_darDeAlta:CiudadPA_DarAltaT")).sendKeys("a");
		driver.findElement(By.id("formularioPA_darDeAlta:codigoPostalPA_DarAltaT")).click();
		driver.findElement(By.id("formularioPA_darDeAlta:codigoPostalPA_DarAltaT")).sendKeys("1");
		driver.findElement(By.id("formularioPA_darDeAlta:PaisPA_DarAltaT")).click();
		driver.findElement(By.id("formularioPA_darDeAlta:PaisPA_DarAltaT")).sendKeys("a");
		driver.findElement(By.id("formularioPA_darDeAlta:NombreIPA_DarAltaT")).click();
		driver.findElement(By.id("formularioPA_darDeAlta:NombreIPA_DarAltaT")).sendKeys("paTestN");
		driver.findElement(By.id("formularioPA_darDeAlta:ApellidoIPA_DarAltaT")).click();
		driver.findElement(By.id("formularioPA_darDeAlta:ApellidoIPA_DarAltaT")).sendKeys("paTestA");
		driver.findElement(By.id("formularioPA_darDeAlta:EnviarPA_DarAlta")).click();
		driver.findElement(By.id("form_administrativo_inicio:AutorizacionPAAdmin")).click();
		driver.findElement(By.id("form_modificar_lista_cuentas:SeleccionarTipoPa_añadirPautT")).click();
		driver.findElement(By.id("form_modificar_lista_cuentas:SeleccionarTipoPa_añadirPautT")).sendKeys("test");
		driver.findElement(By.id("form_modificar_lista_cuentas:CrearAutorizacion_añadirAut")).click();
		assertThat(driver.findElement(By.id("form_administrativo_inicio:UsuarioAdmin")).getText(), is("ponciano"));
		driver.close();
	}

	@Test
	@Requisitos({"RF9"})
	//comprueba si puedes dar de baja a una cuenta, si se redirige al panel administrativos habia exito
	public void cerrarCuenta() {
		driver.get(baseURL+"admin.xhtml");
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("loginAD:loginUsername")).click();
		driver.findElement(By.id("loginAD:loginUsername")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginPassword")).click();
		driver.findElement(By.id("loginAD:loginPassword")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginBotonAD")).click();
		driver.findElement(By.id("form_administrativo_inicio:DarBajaCuentaAdmin")).click();
		driver.findElement(By.cssSelector(
				"#formularioCuenta_darDeBaja\\3AListaPooled_darBaja\\3A 1\\3ASeleccionarPooled_darBaja > .ui-button-text"))
				.click();
		assertThat(driver.findElement(By.id("form_administrativo_inicio:UsuarioAdmin")).getText(), is("ponciano"));
		driver.close();
	}

	@Test
	@Requisitos({"RF8"})
	public void darBajaAutorizado() {
		//comprueba si puedes dar de baja a una persona autorizada, si se redirige al panel administrativos habia exito
		driver.get(baseURL+"admin.xhtml");
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("loginAD:loginUsername")).click();
		driver.findElement(By.id("loginAD:loginUsername")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginPassword")).click();
		driver.findElement(By.id("loginAD:loginPassword")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginBotonAD")).click();
		driver.findElement(By.id("form_administrativo_inicio:DarBajaAdmin")).click();
		driver.findElement(By.cssSelector(
				"#formularioUsuario_darDeBaja\\3AListaPAut_darBaja\\3A 0\\3ASeleccionarPAut_darBaja > .ui-button-text"))
				.click();
		assertThat(driver.findElement(By.id("form_administrativo_inicio:UsuarioAdmin")).getText(), is("ponciano"));
		driver.close();
	}

	@Test
	@Requisitos({"RF4"})
	//comprueba si puedes dar de baja a un cliente, si se redirige al panel administrativos habia exito
	public void darBajaCliente() {
		driver.get(baseURL+"admin.xhtml");
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("loginAD:loginUsername")).click();
		driver.findElement(By.id("loginAD:loginUsername")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginPassword")).click();
		driver.findElement(By.id("loginAD:loginPassword")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginBotonAD")).click();
		driver.findElement(By.id("form_administrativo_inicio:DarBajaAdmin")).click();
		driver.findElement(By.cssSelector(
				"#formularioUsuario_darDeBaja\\3AListaInd_darBaja\\3A 1\\3ASeleccionarInd_darBaja > .ui-button-text"))
				.click();
		assertThat(driver.findElement(By.id("form_administrativo_inicio:UsuarioAdmin")).getText(), is("ponciano"));
		driver.close();
	}

	@Test
	@Requisitos({"RF7"})
	//comprueba si puedes modificar los datos de una persona autorizada, si se redirige al panel administrativos habia exito
	public void modificarAutorizado() {
		driver.get(baseURL+"admin.xhtml");
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("loginAD:loginUsername")).click();
		driver.findElement(By.id("loginAD:loginUsername")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginPassword")).click();
		driver.findElement(By.id("loginAD:loginPassword")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginBotonAD")).click();
		driver.findElement(By.id("form_administrativo_inicio:ModificarClienteAdmin")).click();
		driver.findElement(By.cssSelector(
				"#form_modificar_lista_Usuarios\\3AListaPAut_modificar\\3A 0\\3ASeleccionarPAut_modificar > .ui-button-text"))
				.click();
		driver.findElement(By.cssSelector("tr:nth-child(9)")).click();
		driver.findElement(By.id("formulario_modificar_Persona_Autorizada:ApellidoIPA_modificar2T")).sendKeys("Perez");
		driver.findElement(By.id("formulario_modificar_Persona_Autorizada:TerminarPA_modificar")).click();
		assertThat(driver.findElement(By.id("form_administrativo_inicio:UsuarioAdmin")).getText(), is("ponciano"));
		driver.close();
	}

	@Test
	@Requisitos({"RF4"})
	//comprueba si puedes dar de baja a un clienta, pero falla y permanece en la pagina
	public void darBajaClienteFallo() {
		driver.get(baseURL+"admin.xhtml");
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("loginAD:loginUsername")).click();
		driver.findElement(By.id("loginAD:loginUsername")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginPassword")).click();
		driver.findElement(By.id("loginAD:loginPassword")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginBotonAD")).click();
		driver.findElement(By.id("form_administrativo_inicio:DarBajaAdmin")).click();
		driver.findElement(By.cssSelector(
				"#formularioUsuario_darDeBaja\\3AListaInd_darBaja\\3A 0\\3ASeleccionarInd_darBaja > .ui-button-text"))
				.click();
		driver.findElement(By.cssSelector("ul:nth-child(11) > li")).click();
		assertThat(driver.findElement(By.cssSelector("ul:nth-child(11) > li")).getText(),
				is("Tiene cuenta ya asociada"));
	}

	@Test
	@Requisitos({"RF3"})
	//comprueba si puedes modificar los datos de un cliente, si se redirige al panel administrativos habia exito
	public void modificarInd() {
		driver.get(baseURL+"admin.xhtml");
		driver.manage().window().setSize(new Dimension(3000, 3000));
		driver.findElement(By.id("loginAD:loginUsername")).click();
		driver.findElement(By.id("loginAD:loginUsername")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginPassword")).click();
		driver.findElement(By.id("loginAD:loginPassword")).sendKeys("ponciano");
		driver.findElement(By.id("loginAD:loginBotonAD")).click();
		driver.findElement(By.id("form_administrativo_inicio:ModificarClienteAdmin")).click();
		driver.findElement(By.id("form_modificar_lista_Usuarios:ListaInd_modificar:0:NombreInd_modificar")).click();
		driver.findElement(By.id("form_modificar_lista_Usuarios:ListaInd_modificar:0:NombreInd_modificar")).click();
		{
			WebElement element = driver
					.findElement(By.id("form_modificar_lista_Usuarios:ListaInd_modificar:0:NombreInd_modificar"));
			Actions builder = new Actions(driver);
			builder.doubleClick(element).perform();
		}
		assertThat(driver.findElement(By.id("form_modificar_lista_Usuarios:ListaInd_modificar:0:NombreInd_modificar"))
				.getText(), is("Juan"));
		driver.findElement(By.cssSelector(
				"#form_modificar_lista_Usuarios\\3AListaInd_modificar\\3A 0\\3ASeleccionarInd_modificar > .ui-button-text"))
				.click();
		driver.findElement(By.id("formulario_modificar_individual:NombreIInd_modificar2")).click();
		driver.findElement(By.id("formulario_modificar_individual:NombreIInd_modificar2")).sendKeys("JuanMod");
		driver.findElement(By.id("formulario_modificar_individual:TerminarInd_modificar")).click();
		assertThat(driver.findElement(By.id("form_administrativo_inicio:UsuarioAdmin")).getText(), is("ponciano"));
		driver.close();
	}
}
