package es.uma.proyecto.tests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;

public class x2IT {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	
	private static final String UNIDAD_PERSISTENCIA_PRUEBAS = "proyectoIT";

	
	private static String baseURL;
	private static Map<String,String> propiedadesExtra = new HashMap<>();

	
	@BeforeClass
	public static void setupClass() {
		String server = "localhost";
		try (InputStream is = x2IT.class.getClassLoader().getResourceAsStream("pom.properties")) {
			Properties pomProperties = new Properties();
			pomProperties.load(is);
			server = pomProperties.getProperty("server.host");
			String databaseURL = "jdbc:mysql://" + server + ":3306/sii";
			propiedadesExtra.put("javax.persistence.jdbc.url", databaseURL);
		} catch (IOException e) {
			e.printStackTrace();
		}
		baseURL = "http://" + server + ":8080/DigitalSolutions-war/";
	}
	
	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA_PRUEBAS, propiedadesExtra);
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void logIn() {
		driver.get(baseURL + "index.xhtml");
		driver.manage().window().setSize(new Dimension(1267, 1111));
		driver.findElement(By.id("login:loginUsername")).click();
		driver.findElement(By.id("login:loginUsername")).sendKeys("testU");
		driver.findElement(By.id("login:loginPassword")).click();
		driver.findElement(By.id("login:loginPassword")).sendKeys("test");
		driver.findElement(By.id("login:loginBoton")).click();
		driver.findElement(By.cssSelector("th:nth-child(1)")).click();
		assertThat(driver.findElement(By.cssSelector("th:nth-child(1)")).getText(), is("NIF Empresa"));
	}
}
